[server]
host = "localhost"
port = "8888"

[db]
host = "localhost"
port_graphql = "8080"
port_grpc = "9080"
api = "graphql"
admin = "admin"

[graphql]
complexity_limit = 200  # 50
introspection = false
